import Head from 'next/head'
import Hero from '@/components/Hero/Hero'
import Header from '@/components/Header/Header'
import Services from '@/components/Services/Services'
import Purpose from '@/components/Purpose/Purpose'
import Banner from '@/components/Banner/Banner'
import Download from '@/components/Download/Download'

export default function Home() {
  return (
    <>
      <Head>
        <title>MeuTudo App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Header />
        <Hero />
        <Services />
        <Purpose />
        <Banner />
        <Download />
        <Footer />
      </>
    </>
  )
}
